######################################################################
# Automatically generated by qmake (2.01a) s�b mar 29 15:27:15 2014
######################################################################

QT       += core network
TARGET = QBonjour
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app

!mac:LIBS += -ldns_sdDEPENDPATH += . bonjour network
INCLUDEPATH += . network bonjour

OTHER_FILES += \
    test.png

# Input
#WislandService.hpp \
#ChatClient.h \
HEADERS += WislandService.hpp \
           applicationinfo.hpp \
           bonjour/Record.hpp \
           bonjour/RecordPrivate.hpp \
           bonjour/ServiceBrowser.hpp \
           bonjour/ServiceRegister.hpp \
           bonjour/ServiceResolver.hpp \
           network/Action.hpp \
           network/Consumer.hpp \
           network/P2PService.h \
           network/Serializable.hpp \
           network/ServiceConnection.hpp
SOURCES += main.cpp \
           #ChatClient.cpp \
           WislandService.cpp \
           bonjour/Record.cpp \
           bonjour/ServiceBrowser.cpp \
           bonjour/ServiceRegister.cpp \
           bonjour/ServiceResolver.cpp \
           network/Action.cpp \
           network/Consumer.cpp \
           network/P2PService.cpp \
           network/Serializable.cpp \
           network/ServiceConnection.cpp

RESOURCES +=
